Server/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  resources :sections
  resources :courses
  resources :majors
  resources :users
  resources :dashboard
  resources :admin
  resources :generaleducationrequirements
  resources :usercourses
  
  get 'register' => 'users#new'
  get 'settings' => 'pages#settings'
  get 'search' => 'pages#searchresults'
  get 'profile' => 'users#show'
  get 'courses' => 'courses#index'
  get 'sections' => 'sections#index'
  get 'majors' => 'major#index'
  
  
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

Server/app/models/major.rb
class Major < ActiveRecord::Base
  has_many :courses
  
end

Server/app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  
  
  def index
    @major = Major.select('DISTINCT major').order('major')
    
    # @major = Major.where('major like ?', '%Chemical%')
    
    @major.each do |major|
      # major.major = 'chemical engineering'
      # major.save
    end
    # render plain: @major.count
  end
  
  
  def new
    @major = Major.new
  end
  
  def show
    
    @courses = []
    
    @major = params[:id].downcase
    @coursesInMajors = Major.where('major like ?', params[:id])
    
    @coursesInMajors.each do |major|
      begin
          @courses.push(major: major ,course: Course.where('name = ?', major.course).take!)
      rescue
        @tempCourse = Course.new(title: major.course,name: major.course)
        @courses.push(major: major, course: @tempCourse)
      end
    end
    
    # render plain: @courses[0].inspect
  end
  
  def edit
    @majors = Major.where('major = ?', params[:id])
    @major = Major.new()
    @major.major = params[:id]
    @courses = Course.all
    @coursesList = []
    @courses.each do |p|
      @coursesList.push(p.name)
    end
    
  end
  
  def update
    @major = Major.find(params[:major_id])
    
    if @major.update(new_params)
      redirect_to majors_url
    else
      render 'edit'
    end
  end
  
  def create
    @major = Major.new(new_params)
    @major.save
    if(params[:async])
      redirect_to majors_path + '/' + @major.major.gsub(' ', '%20') +  '/edit'
    else
      redirect_to majors_path
    end
    
  end
  
  def destroy
    @major = Major.find(params[:id])
    @major.destroy
    
  end
  
  private
    def new_params
      if params[:major]["course"]
        params[:major]["course"] = params[:major]["course"].upcase
      end
      if params[:major]["major"]
        params[:major]["major"] = params[:major]["major"].downcase
      end
      params.require(:major).permit(:major, :course, :year, :semester)
    end
end

Server/app/helpers/majors_helper.rb
module MajorsHelper
end

Server/app/views/majors/edit.html.erb
<div class="row whiteUI">
<div class="container">
<h1 ><a href="<%= majors_path + '/' + @major.major %>"><%= @major.major.titleize %></a></h1>

<h2>Add new</h2>
<%= form_for :major, remote:true, url: majors_path, :html => {:id => "newMajor"} do |f| %>
    <%= f.hidden_field :major %>
    <%= hidden_field_tag(:async, "true") %>
    <p>
      <%= f.label :course %><br>
      <%= f.text_field :course, class: "create_input" %>
    </p>
    <p>
        <%= f.label :year %><br>
        <%= f.select :year, [ '1', '2', '3', '4','5'], :prompt => 'Select One'  %>
      </p>
       <p>
       <%= f.label :semester %><br>
        <%= f.select :semester, [ 'Fall', 'Spring', 'Summer'], :prompt => 'Select One'  %>
      </p>
    <%= f.submit %>
    </p>
<% end %>

<center><div style="width: 90%; height:1px; background-color: gray; margin: 25px 0;"></div></center>

<div class="row">
  <h4><div class="col-md-9">Course</div></h4>
  <h4><div class="col-md-1">Year</div></h4>
  <h4><div class="col-md-1">Semester</div></h4>
  <h4><div class="col-md-1">Remove</div></h4>
</div>
<br/>
<div id="editMajor">
  <% @majors.each do |major| %>
    <div class="row">
      <% if major.course %>
        <%= form_for major, remote:true, url: majors_path + '/' + major.major, method: :patch do |f| %>
           <%= hidden_field_tag(:major_id, major.id) %>
          <div class="col-md-9">
            <%= f.text_field :course, class: "create_input", style: "width:100%" %>
          </div>
          <div class="col-md-1">
            <%= f.select :year, [ '1', '2', '3', '4','5'], :prompt => 'Select One'  %>
          </div>
          <div class="col-md-1">
            <%= f.select :semester, [ 'Fall', 'Spring', 'Summer'], :prompt => 'Select One'  %>
          </div>
          <div class="col-md-1">
            <a class="col-md-2 col-md-offset-2" data-confirm="Are you sure?" data-method="delete" data-remote="true" href="<%=major_path(major)%>" rel="nofollow">
            <span class="glyphicon glyphicon-remove"></span></a>
          </div>
        <%end%>
      <%end%>
    </div>
  <%end%>
  <br/>
</div>
<a class="pull-right btn  btn-lg" id="updateall">Update</a>
<br/>





<script src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>

<script>
$('head').append('<link rel="stylesheet" type="text/css" href="http://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/css/custom-theme/jquery-ui-1.10.3.custom.css" />')
availableTags =  <%=  raw @coursesList.to_json %>

function jqueryLoaded() {
  $.each($('.create_input'), function() {
    $(this).autocomplete({
      source: availableTags
    });
  });
}
function checkJquery() {
    if (window.jQuery && jQuery.ui) {
        jqueryLoaded();
    } else {
        window.setTimeout(checkJquery, 100);
    }
}
$(document).ready(function() {
    
  
    checkJquery();


});
$(document).ready(function() {
  $('#updateall').click(function(){
    $.each($('.edit_major'), function(){
      $(this).submit();
    })
    
  });
  $("#newMajor").on("ajax:success", function(e, data, status, xhr) {
    $('#newMajor input[name="major[course]"]').val('')
    $('#editMajor').html($(data).find('#editMajor').html())
  })
  $("#newMajor").on("ajax:error", function(e, xhr, status, error) {
    $("#newMajor").append("<p>ERROR</p>");
  });
  
  
    $(".edit_major").on("ajax:success", function(e, data, status, xhr) {
      console.log('sucess!')
    })
    $(".edit_major").on("ajax:error", function(e, xhr, status, error) {
      console.log('error')
      $(this).remove()
      
  });
});

</script>



</div>
</div>

Server/app/views/majors/index.html.erb
<div id="editMajor" class="row whiteUI" >
<div class="container">
<h1>Majors</h1>
  <% @major.each do |major| %>
  <% if major.major %>
    <a href="<%= majors_path %>/<%= major.major %>"><%= major.major.titleize %></a><br/>
  <%end%>
  <% end %>
<br/>
 <% if user_admin? %>
 <a class="btn btn-default btn-lg" href=<%= new_major_path %>>New Major</a>
 <%end%>
  
</div>
</div>

Server/app/views/majors/new.html.erb
<div class="row whiteUI">
<div class="container">
<h1><a href="<%= majors_path %>">Majors</a></h1>
  <%= form_for :major, url: majors_path do |f| %>
      <p>
        <%= f.label :major %><br>
        <%= f.text_field :major %>
      </p>
     
      <p>
        <%= f.submit %>
      </p>
    <% end %>
  </div>
</div>

Server/app/views/majors/show.html.erb
<div id="editMajor" class="row whiteUI">
  <div class="container">
  
      <h1><a href="<%= majors_path %>">Majors</a></h1>
    <div  class="row" >
      <div class="col-md-11">
        <h2 style="margin:0" ><%= @major.titleize %></h2>
      </div>
      <div class="col-md-1">
        <% if user_admin? %>
        <a class="btn btn-default" href=<%= edit_major_path(@major) %>><span class="glyphicon glyphicon-edit"></span></a>
        <% end %>
      </div>
    </div>
    
    <div class="table-responsive">
      <table class="table table-striped">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <tr>
          <th>Course</th>
          <th>Title</th>
          <th>Year</th>
          <th>Semester</th>
        </tr>
        <% @courses.each do |current| %>
          <% if current and current[:course].name %>
          <tr>
            <td><%= current[:course].name %></td>
            <%
                #Putting logic in views!
                index = 0
                if current[:course].title
                    index = current[:course].title.index('.')
                    if !index
                      index = 0
                    else index
                      index = index + 1
                  end
                end
            %>
            <% if current[:course].title %>
              <td><%= current[:course].title[index,current[:course].title.length] %></td>
              <% if(current[:major])  %>
                <td><%=current[:major].year%></td>
                <td><%= current[:major].semester %></td>
              <%end%>
            <%end%>
          </tr>
          <%end%>
      <%end %>
      </table>
      </div>
      </div>
    </div>
  </div>