Server/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  resources :sections
  resources :courses
  resources :majors
  resources :users
  resources :dashboard
  resources :admin
  resources :generaleducationrequirements
  resources :usercourses
  
  get 'register' => 'users#new'
  get 'settings' => 'pages#settings'
  get 'search' => 'pages#searchresults'
  get 'profile' => 'users#show'
  get 'courses' => 'courses#index'
  get 'sections' => 'sections#index'
  get 'majors' => 'major#index'
  
  
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

Server/app/models/section.rb
class Section < ActiveRecord::Base
  def self.search(search)
    if search
      search = search.gsub(' ','')
      self.where("name like ?", "%#{search}%")
    end
  end
end

Server/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @section = Section.search(params[:search])
  end
  
  def new
    @section = Section.new
  end
  def create
    @section = Section.new(section_params)
   
    @section.save
    redirect_to @section
  end
  
  def show
    @section = Section.find(params[:id])
  end
  
  def edit
    @section = Section.find(params[:id])
    session[:return_to] ||= request.referer
  end
  
  def update
    @section = Section.find(params[:id])
    
    if @section.update(section_params)
      redirect_to session.delete(:return_to)
    else
      render 'edit'
    end
  end
  
  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    
    redirect_to sections_path
  end
  
  private
    def section_params
      params.require(:section).permit(:title, :name, :section, :courseID, :status, :component, :session, :hour, :classNumber, :startDate, :endDate, :classTime, :location, :instructor, :enrolled, :size, :career, :school, :department, :campus)
      
    end
  
  
end

Server/app/helpers/sections_helper.rb
module SectionsHelper
end

Server/app/views/sections/_form.html.erb
<%= form_for @section do |f| %>
<div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :section %><br/>
    <%= f.text_field :section, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :courseID %><br/>
    <%= f.text_field :courseID, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br/>
    <%= f.text_field :status, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :component %><br/>
    <%= f.text_field :component, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :session %><br/>
    <%= f.text_field :session, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :hour %><br/>
    <%= f.text_field :hour, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :classNumber %><br/>
    <%= f.text_field :classNumber, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :startDate %><br/>
    <%= f.text_field :startDate, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :endDate %><br/>
    <%= f.text_field :endDate, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :classTime %><br/>
    <%= f.text_field :classTime, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br/>
    <%= f.text_field :location, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :instructor %><br/>
    <%= f.text_field :instructor, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :enrolled %><br/>
    <%= f.text_field :enrolled, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :size %><br/>
    <%= f.text_field :size, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :career %><br/>
    <%= f.text_field :career, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :school %><br/>
    <%= f.text_field :school, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :department %><br/>
    <%= f.text_field :department, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :campus %><br/>
    <%= f.text_field :campus, :class=>"form-control" %>
  </div>
  <%= f.submit 'Save', :style => "margin-top:15px", :class => 'pull-right btn btn-lg btn-default' %>
  
<%end%>

Server/app/views/sections/edit.html.erb
<div class="row whiteUI">
<div class="container">
<%= render 'form'%>

</div>
</div>

Server/app/views/sections/index.html.erb
<script type="text/javascript">
function test() {
    sections = <%= raw @section.to_json -%>;
    
    alert(sections[1])
}
</script>

<div class="row whiteUI">
  <div class="container">
    <h1 style="margin-top:0">Sections</h1>
      
    
    
    <%= form_tag(sections_path, method: :get, :class=> "form-inline") do %>
    <div class="form-group">
    <%= text_field_tag :search, "", placeholder: "Course", :class=>"form-control"  %>
    <button type="button" type="submit" class="btn btn-default">
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </button>
    </div>
    <% end %>
    <div style="padding:10px"></div><!-- seperator -->
    <% if @section and @section.count > 0 %>
       <% @section.each do |a| %>
        <%= link_to (a.name + '-' + a.section), a %>
        
        <br/>
         
      <% end %>
    <%end%>
    <% if user_admin? %>
    <a class="btn btn-lg btn-default" href=<%= new_section_path %>><span class="glyphicon glyphicon-plus"></span> New</a>
    <%end%>
  </div>
</div>

Server/app/views/sections/new.html.erb
<div class="row whiteUI">
<div class="container">
  <h1> New section </h1>
  <%= render 'form'%>


</div>
</div>

Server/app/views/sections/show.html.erb
<div class="row whiteUI">
<div class="container">
<div class="row">
  <div class="col-md-10">
    <h1 style="margin:0" ><%= @section.title %><br/>
    <small><%= @section.name.insert(4, ' ') + ' - ' + @section.section %></small></h1>
  </div>
  <div class="col-md-2">
  <% if user_admin? %>
    <a class="btn btn-lg btn-default" href=<%= edit_section_path(@section) %>><span class="glyphicon glyphicon-edit"></span></a>
    <a class="btn btn-lg btn-default " data-confirm="Are you sure?" rel="nofollow" data-method="delete" href=<%= section_path(@section) %>><span class="glyphicon glyphicon-remove"></span>
    </a>
    <%end%>
  </div>
</div>
<% if @section.status? %>
  <h4>Status: <%= @section.status %> </h4>
<%end%>
<% if @section.component? %>
  <h4>Component: <%= @section.component %> </h4>
<%end%>
<% if @section.session? %>
  <h4>Session: <%= @section.session %> </h4>
<%end%>
<% if @section.hour? %>
  <h4>Hours: <%= @section.hour %> </h4>
<%end%>
<% if @section.classNumber? %>
  <h4>ClassNumber: <%= @section.classNumber %> </h4>
<%end%>
<% if @section.startDate? and @section.endDate? %>
  <h4>Date: <%= @section.startDate %> -  <%= @section.endDate %></h4>
<%end%>
<% if @section.classTime? %>
  <h4>Class Time: <%= @section.classTime %> </h4>
<%end%>
<% if @section.location? %>
  <h4>Location: <%= @section.location %> </h4>
<%end%>
<% if @section.instructor? %>
  <h4>Instructor: <%= @section.instructor %> </h4>
<%end%>
<% if @section.enrolled? %>
  <h4>Enrolled: <%= @section.enrolled %> </h4>
<%end%>
<% if @section.size? %>
  <h4>Size: <%= @section.size %> </h4>
<%end%>
<% if @section.career? %>
  <h4>Career: <%= @section.career %> </h4>
<%end%>
<% if @section.school? %>
  <h4>School: <%= @section.school %> </h4>
<%end%>
<% if @section.department? %>
<h4>department: <%= @section.department %> </h4>
<%end%>
<% if @section.campus? %>
<h4>campus: <%= @section.campus %> </h4>
<%end%>

</div>
</div>