Server/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  resources :sections
  resources :courses
  resources :majors
  resources :users
  resources :dashboard
  resources :admin
  resources :generaleducationrequirements
  resources :usercourses
  
  get 'register' => 'users#new'
  get 'settings' => 'pages#settings'
  get 'search' => 'pages#searchresults'
  get 'profile' => 'users#show'
  get 'courses' => 'courses#index'
  get 'sections' => 'sections#index'
  get 'majors' => 'major#index'
  
  
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

Server/app/models/general_education_requirement.rb
class GeneralEducationRequirement < ActiveRecord::Base
end

Server/app/controllers/generaleducationrequirements_controller.rb
class GeneraleducationrequirementsController < ApplicationController
  def index
    @GeneralEducationRequirement = GeneralEducationRequirement.all
    
  end
  
  def new
    @GeneralEducationRequirement = GeneralEducationRequirement.new
  end
  
  def create
    @GeneralEducationRequirement = GeneralEducationRequirement.new(my_params)
   
    @GeneralEducationRequirement.save
    redirect_to generaleducationrequirements_path
  end
  
  def update
    @GeneralEducationRequirement = GeneralEducationRequirement.find(params[:id])
    if @GeneralEducationRequirement.update(my_params)
      redirect_to generaleducationrequirements_path
    else
      render 'edit'
    end
  end
  
  def edit
    @GeneralEducationRequirement = GeneralEducationRequirement.find(params[:id])
  end
  
  def destroy
    @GeneralEducationRequirement = GeneralEducationRequirement.find(params[:id])
    @GeneralEducationRequirement.destroy
 
    redirect_to generaleducationrequirements_path
  end

    
  private
    def my_params
      # In the future don't freaking name models with camel case just one big headache, AND DONT GIVE THEM SUCH A LONG NAME CORY! >:(
      if(params[:GeneralEducationRequirement])
        params.require(:GeneralEducationRequirement).permit(:course, :requirement)
      else
        params.require(:general_education_requirement).permit(:course, :requirement)
      end
    end
  
end

Server/app/helpers/general_education_requirements_helper.rb
module GeneralEducationRequirementsHelper
end

Server/app/views/generaleducationrequirements/edit.html.erb
<div class="row whiteUI">
<div class="container">
<h1 style="margin:0">New requirement</h1>

<%= form_for :GeneralEducationRequirement, url: generaleducationrequirement_path(@GeneralEducationRequirement), method: :patch do |f|  %>
  <div class="form-group">
    <%= f.label :course %><br/>
    <%= f.text_field :course, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :requirement %><br/>
    <%= f.text_field :requirement, :class=>"form-control" %>
  </div>
  
  <%= f.submit 'Save', :style => "margin-top:15px", :class => 'pull-right btn btn-lg btn-default' %>
<%end%>


</div>
</div>

Server/app/views/generaleducationrequirements/index.html.erb
<div class="row whiteUI">
<div class="container">
<div class="row">
  <div class="col-md-10">
    <h1 style="margin-top:0">General education requirements</h1>
  </div>
  <div class="col-md-2">
    <% if user_admin? %>
      <a class="btn  btn-default" href=<%= new_generaleducationrequirement_path %>><span class="glyphicon glyphicon-plus"></span> New</a>
    <%end%>
  </div>
</div>

<table class="table table-striped table-hover">
    <tr>
      <td>Course</td>
      <td>Requirement</td>
      <% if user_admin? %>
        <td>Edit</td>
        <td>Remove</td>
      <%end%>
    </tr>
   <% @GeneralEducationRequirement.each do |requirement| %>
    <tr>
      <td><%= requirement.course %></td>
      <td><%= requirement.requirement %></td>
      <% if user_admin? %>
      <td><a class="btn btn-default btn-xs" href=<%= edit_generaleducationrequirement_path(requirement) %>><span class="glyphicon glyphicon-edit"></span></a></td>
      <td><a class="btn btn-default btn-xs" data-confirm="Are you sure?" rel="nofollow" data-method="delete" href=<%= generaleducationrequirement_path(requirement) %>><span class="glyphicon glyphicon-remove"></span></a></td>
      <%end%>
    </tr>
    
  <%end%>
</table>
  
</div>
</div>

Server/app/views/generaleducationrequirements/new.html.erb
<div class="row whiteUI">
<div class="container">
<h1 style="margin:0">New requirement</h1>

<%= form_for(@GeneralEducationRequirement, url: generaleducationrequirements_path) do |f| %>
  <div class="form-group">
    <%= f.label :course %><br/>
    <%= f.text_field :course, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :requirement %><br/>
    <%= f.text_field :requirement, :class=>"form-control" %>
  </div>
  
  <%= f.submit 'Save', :style => "margin-top:15px", :class => 'pull-right btn btn-lg btn-default' %>
<%end%>


</div>
</div>