Server/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  resources :sections
  resources :courses
  resources :majors
  resources :users
  resources :dashboard
  resources :admin
  resources :generaleducationrequirements
  resources :usercourses
  
  get 'register' => 'users#new'
  get 'settings' => 'pages#settings'
  get 'search' => 'pages#searchresults'
  get 'profile' => 'users#show'
  get 'courses' => 'courses#index'
  get 'sections' => 'sections#index'
  get 'majors' => 'major#index'
  
  
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

Server/app/views/shared/_footer.html.erb
<div class="row footer">
    <div class="col-md-12">
        <h4>Built and designed in Fayetteville,    Version 1.0</h4>
        <h4>-----------------------------------------------------</h4>
        <h4>Copyright 2014 &copy; Cory McDonald - Matt Luther - Will Turner - Lucas Dorrough</h4>
    </div>
</div>

Server/app/views/shared/_loginform.html.erb
<%= form_for(:session, url: login_path) do |f| %>
    <div class="form-group">
        <label>Email</label>
        <%= f.text_field :email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <label>Password</label>
        <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.submit "Log in", class: "btn btn-primary btn-lg" %>
        <a class="btn btn-primary btn-lg" href='register' role="button">Register</a>
    </div>
<% end %>

Server/app/views/shared/_navigation.html.erb
<script>
$(document).ready(function() {
  $('.dropdown').on('show.bs.dropdown', function(e){
    $(this).find('.dropdown-menu').first().stop(true, true).slideDown();
  });

  $('.dropdown').on('hide.bs.dropdown', function(e){
    $(this).find('.dropdown-menu').first().stop(true, true).slideUp();
  });
});
</script>


<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid blackUI">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href='/'> <img class="brandIMG"src="/assets/NamelogoS.png"></a>
    </div>
  
  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(courses_path, method: :get, class: "navbar-form navbar-right")  do %>
        <%= text_field_tag :search, nil, :class => 'form-control' %>
        <%= submit_tag "Search", class: "btn btn-default"%>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href='/dashboard' style="">Create Schedule</a></li>
        <li><a href='/courses'>Courses</a></li>
        <li><a href="/majors">Majors</a></li>
          <li class="dropdown">
          <% if logged_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.firstName %> <%= current_user.lastName %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", usercourses_path %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Server/app/views/shared/_registerform.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>